"""Multi-modal fusion of image evidence with clinical risk factors.

WHY THIS REPLACES THE OLD WEIGHTED SUM
--------------------------------------
The original fusion was ``0.7*p_img + 0.15*(bmi/40) + 0.15*(years/30)``:

  * ``age`` was collected by the form, posted to the API and passed into the
    function -- then never referenced. One of the three advertised clinical
    inputs did nothing.
  * probabilities were averaged with unbounded ratios. A perfectly healthy foot
    (p_img = 0.00) with BMI 40 and 30 years of diabetes scored 0.30, landing on
    the MEDIUM boundary purely on demographics.
  * the output was labelled "SHAP values", but a hand-picked weighted average
    is not a Shapley decomposition of anything.

This module instead combines evidence in **log-odds space**, which is the
mathematically correct way to update a probability with independent evidence:

    z = logit(p_image) + SUM_i beta_i * (x_i - reference_i)
    p_fused = sigmoid(z)

Two properties fall out of that, both of which are testable and are asserted in
``_self_check`` below:

  1. With every clinical factor at its population reference, ``p_fused ==
     p_image`` exactly. Clinical history *modulates* image evidence rather than
     being averaged against it.
  2. The model is additive, so its **exact** Shapley values are available in
     closed form -- phi_i = beta_i * (x_i - reference_i) -- with no sampling and
     no approximation. The attribution reported here is a real Shapley
     decomposition of the fused log-odds.

HONESTY NOTE ON THE COEFFICIENTS
--------------------------------
The DFU patch dataset contains images only -- no patient metadata whatsoever.
These coefficients are therefore **NOT fitted from this dataset**; they are
illustrative priors set from published odds ratios in the diabetic-foot
literature (see references below). They are a transparent, defensible
placeholder for a model that would be fitted on a linked clinical cohort. Any
report generated by this system must carry that caveat, and
``fuse()`` returns ``coefficients_fitted: False`` so downstream code cannot
quietly forget it.

References for the order of magnitude of each odds ratio:
  * Boulton et al., "Comprehensive Foot Examination and Risk Assessment",
    Diabetes Care 31(8), 2008.
  * IWGDF Guidelines on the Prevention of Foot Ulcers in Persons with
    Diabetes, 2023 update.
  * Monteiro-Soares et al., "Predictive factors for diabetic foot ulceration:
    a systematic review", Diabetes Metab Res Rev 28(7), 2012.
"""
import math

# Probability clamp. logit(0) and logit(1) are infinite, and a CNN that is
# 100% certain is certainly wrong, so image evidence is capped at ~19:1 odds.
EPS = 0.05


def logit(p):
    p = min(max(float(p), EPS), 1.0 - EPS)
    return math.log(p / (1.0 - p))


def sigmoid(z):
    if z >= 0:                      # numerically stable both directions
        return 1.0 / (1.0 + math.exp(-z))
    e = math.exp(z)
    return e / (1.0 + e)


def _bmi_excess(bmi):
    """U-shaped BMI risk: both obesity and underweight raise ulcer risk.

    Returns 'units of risk away from the healthy 22-25 band', so a single
    coefficient covers both tails.
    """
    if bmi > 25.0:
        return bmi - 25.0
    if bmi < 22.0:
        return (22.0 - bmi) * 1.5   # underweight/frailty carries steeper risk
    return 0.0


# The REFERENCE PROFILE against which every contribution is measured: a
# 60-year-old with 10 years of diagnosed diabetes, BMI inside the healthy 22-25
# band, HbA1c 7.0%, and no neuropathy, PAD, prior ulcer or smoking history. Such
# a patient shifts the image evidence by exactly zero. The BMI reference is 0.0
# because _bmi_excess already returns distance from the healthy band rather than
# a raw BMI value.
#
# name -> (label, coefficient in log-odds per unit, reference value,
#          transform applied to the raw input, unit string)
FACTORS = {
    "diabetes_years": ("Diabetes Duration", math.log(1.05), 10.0, float, "years"),
    "age":            ("Patient Age",       math.log(1.02), 60.0, float, "years"),
    "bmi":            ("Body Mass Index",   math.log(1.04),  0.0, _bmi_excess, "kg/m²"),
    "hba1c":          ("HbA1c (glycaemic control)", math.log(1.25), 7.0, float, "%"),
    "neuropathy":     ("Peripheral Neuropathy", math.log(3.0), 0.0, float, ""),
    "pad":            ("Peripheral Arterial Disease", math.log(2.5), 0.0, float, ""),
    "prior_ulcer":    ("Prior Ulcer / Amputation", math.log(3.5), 0.0, float, ""),
    "smoker":         ("Active Smoker", math.log(1.6), 0.0, float, ""),
}

# Clinical history should inform, not overrule, the pixels. Without this the
# eight factors can swamp the image term and the system stops being a vision
# system. +-2.0 logits is a ~7.4x odds swing in either direction.
MAX_CLINICAL_SHIFT = 2.0

RISK_BANDS = [(0.66, "HIGH"), (0.33, "MEDIUM"), (0.0, "LOW")]


def risk_band(p):
    for threshold, label in RISK_BANDS:
        if p >= threshold:
            return label
    return "LOW"


def iwgdf_category(neuropathy=0, pad=0, prior_ulcer=0, deformity=0):
    """IWGDF 2023 risk stratification -- verbatim from the published guideline.

    Unlike the fusion coefficients this is not a heuristic: it is the actual
    screening-interval rule clinicians use, so it is reproduced exactly.
    """
    if prior_ulcer:
        return {"category": 3, "label": "Very high risk",
                "screening_interval": "Every 1-3 months",
                "basis": "History of foot ulcer or lower-extremity amputation"}
    if neuropathy and (pad or deformity):
        return {"category": 2, "label": "High risk",
                "screening_interval": "Every 3-6 months",
                "basis": "Loss of protective sensation with PAD and/or foot deformity"}
    if neuropathy or pad:
        return {"category": 1, "label": "Moderate risk",
                "screening_interval": "Every 6-12 months",
                "basis": "Loss of protective sensation or peripheral arterial disease"}
    return {"category": 0, "label": "Low risk",
            "screening_interval": "Annually",
            "basis": "No loss of protective sensation and no PAD"}


def fuse(p_image, **clinical):
    """Combine calibrated image probability with clinical covariates.

    Every clinical argument is optional. Anything omitted or None is treated as
    sitting at its population reference, contributing exactly zero -- so a
    missing field can never silently push risk in either direction.
    """
    z_image = logit(p_image)
    contributions, present = [], {}

    for key, (label, beta, ref, transform, unit) in FACTORS.items():
        raw = clinical.get(key)
        if raw is None:
            continue
        try:
            value = transform(raw)
        except (TypeError, ValueError):
            continue
        present[key] = raw
        phi = beta * (value - ref)
        contributions.append({
            "feature": label, "key": key, "value": raw, "unit": unit,
            "logit_contribution": round(phi, 4),
            "odds_ratio": round(math.exp(phi), 3),
            "direction": "increases risk" if phi > 0 else
                         ("decreases risk" if phi < 0 else "neutral"),
        })

    raw_shift = sum(c["logit_contribution"] for c in contributions)
    shift = max(-MAX_CLINICAL_SHIFT, min(MAX_CLINICAL_SHIFT, raw_shift))
    if raw_shift != 0 and shift != raw_shift:
        # Scale contributions proportionally so the reported attributions still
        # sum to the shift that was actually applied.
        scale = shift / raw_shift
        for c in contributions:
            c["logit_contribution"] = round(c["logit_contribution"] * scale, 4)
            c["odds_ratio"] = round(math.exp(c["logit_contribution"]), 3)

    z = z_image + shift
    p_fused = sigmoid(z)

    # Exact Shapley attribution. For an additive model the Shapley value of a
    # feature is simply its own term measured against the reference, and the
    # values sum to f(x) - f(reference). Reported as a share of total absolute
    # influence so the UI can draw comparable bars.
    attribution = [{"feature": "CNN Visual Evidence", "key": "image",
                    "logit_contribution": round(z_image, 4),
                    "value": round(p_image, 4), "unit": "P(ulcer)",
                    "odds_ratio": round(math.exp(z_image), 3),
                    "direction": "increases risk" if z_image > 0 else "decreases risk"}]
    attribution += contributions
    total_abs = sum(abs(a["logit_contribution"]) for a in attribution) or 1.0
    for a in attribution:
        a["influence_pct"] = round(abs(a["logit_contribution"]) / total_abs * 100, 1)
    attribution.sort(key=lambda a: -a["influence_pct"])

    p_used = sigmoid(z_image)   # what the fusion actually consumed, post-clamp
    return {
        "risk_probability": round(p_fused, 4),
        "risk": risk_band(p_fused),
        "image_probability": round(float(p_image), 4),
        # A CNN trained on ~700 images asserting 0.999 certainty is overstating
        # its evidence, so image probability is capped at EPS..1-EPS before it
        # enters log-odds space. Surfaced rather than hidden, because otherwise
        # risk_probability quietly disagrees with image_probability.
        "image_probability_used": round(p_used, 4),
        "image_probability_clamped": abs(p_used - float(p_image)) > 1e-6,
        "clinical_logit_shift": round(shift, 4),
        "clinical_shift_clamped": shift != raw_shift,
        "fused_logit": round(z, 4),
        "attribution": attribution,
        "factors_supplied": sorted(present),
        "iwgdf": iwgdf_category(
            neuropathy=clinical.get("neuropathy") or 0,
            pad=clinical.get("pad") or 0,
            prior_ulcer=clinical.get("prior_ulcer") or 0,
            deformity=clinical.get("deformity") or 0,
        ),
        "coefficients_fitted": False,
        "coefficient_source": "Literature-informed priors; NOT fitted on this dataset",
    }


def _self_check():
    """The properties that make this model defensible, asserted."""
    # 1. reference profile is a no-op: clinical history modulates, never replaces
    r = fuse(0.42, age=60, bmi=23.5, diabetes_years=10)
    assert abs(r["risk_probability"] - 0.42) < 1e-3, r["risk_probability"]
    assert abs(r["clinical_logit_shift"]) < 1e-9, r

    # 2. the old bug: age must actually move the output
    lo = fuse(0.5, age=30)["risk_probability"]
    hi = fuse(0.5, age=85)["risk_probability"]
    assert hi > lo, f"age is being ignored again ({lo=}, {hi=})"

    # 3. a clean image is not dragged into MEDIUM by demographics alone.
    #    This exact profile scored 0.30 -> MEDIUM under the old weighted sum.
    r = fuse(0.02, age=70, bmi=40, diabetes_years=30)
    assert r["risk"] == "LOW", (r["risk"], r["risk_probability"])

    # 4. omitted fields contribute exactly nothing
    assert fuse(0.7)["risk_probability"] == fuse(0.7, hba1c=None, pad=None)["risk_probability"]
    assert fuse(0.7)["clinical_logit_shift"] == 0.0
    # with no clinical input the fused risk IS the (clamped) image probability
    r = fuse(0.7)
    assert abs(r["risk_probability"] - r["image_probability_used"]) < 1e-3
    assert not r["image_probability_clamped"]
    # over-confident input is clamped, and the clamp is reported not hidden
    r = fuse(0.999)
    assert r["image_probability_clamped"] and r["image_probability"] == 0.999
    assert abs(r["image_probability_used"] - (1 - EPS)) < 1e-3, r["image_probability_used"]

    # 5. Shapley values are exact: contributions sum to the applied shift
    r = fuse(0.5, age=75, bmi=34, diabetes_years=22, hba1c=9.5, neuropathy=1)
    s = sum(a["logit_contribution"] for a in r["attribution"] if a["key"] != "image")
    assert abs(s - r["clinical_logit_shift"]) < 1e-3, (s, r["clinical_logit_shift"])
    assert abs(r["fused_logit"] - (logit(0.5) + r["clinical_logit_shift"])) < 1e-6

    # 6. clamping holds even when every risk factor is maxed, and the
    #    attributions are rescaled to still sum to the applied shift
    r = fuse(0.5, age=95, bmi=50, diabetes_years=45, hba1c=14,
             neuropathy=1, pad=1, prior_ulcer=1, smoker=1)
    assert r["clinical_shift_clamped"] and r["clinical_logit_shift"] == MAX_CLINICAL_SHIFT
    s = sum(a["logit_contribution"] for a in r["attribution"] if a["key"] != "image")
    assert abs(s - MAX_CLINICAL_SHIFT) < 1e-2, s

    # 7. BMI risk is U-shaped -- underweight is a risk factor, not a protection
    mid = fuse(0.5, bmi=23)["risk_probability"]
    assert fuse(0.5, bmi=16)["risk_probability"] > mid
    assert fuse(0.5, bmi=38)["risk_probability"] > mid

    # 8. probabilities stay in range under absurd input
    for p in (0.0, 1.0, 0.5):
        v = fuse(p, age=200, bmi=0.1, diabetes_years=-5)["risk_probability"]
        assert 0.0 < v < 1.0, v

    # 9. monotone in image evidence, all else equal
    seq = [fuse(p, age=70, hba1c=8)["risk_probability"] for p in (0.1, 0.3, 0.6, 0.9)]
    assert seq == sorted(seq), seq

    # 10. IWGDF ladder matches the published rule
    assert iwgdf_category()["category"] == 0
    assert iwgdf_category(neuropathy=1)["category"] == 1
    assert iwgdf_category(pad=1)["category"] == 1
    assert iwgdf_category(neuropathy=1, pad=1)["category"] == 2
    assert iwgdf_category(neuropathy=1, deformity=1)["category"] == 2
    assert iwgdf_category(prior_ulcer=1)["category"] == 3
    assert iwgdf_category(neuropathy=1, pad=1, prior_ulcer=1)["category"] == 3

    print("clinical.py self-check passed")


if __name__ == "__main__":
    _self_check()
